### ISSUE TITLE
`No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by greeven** [kfleischmann/geekhub#2]
**Problem:** If I open `testings/index.html` the console output in the browser is this:

```No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.```

**Quickfix:** There is a plugin for [chrome](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi).

**Probable Solution:** The server should take care of this.

**Comment by greeven** [comment]
No I work on the feature-test-branch and open the index.html in the browser.
I meant the browser console.
Sry for the confusion.

**Comment by kfleischmann** [comment]
okay. i see. But i am not able to reproduce the problem on my installation. Maybe you could try to upgrade the chrome version to the latest?

**Comment by greeven** [comment]
My chrome version is up to date: Version 69.0.3497.100 (Offizieller Build) (64-Bit)
I see the same behaviour in Firefox  (v62.0).

Might be - for some reason - my machine. I'll try it out on a different machine later.
