### ISSUE TITLE
Setup on Ubuntu Server

### ISSUE THREAD

**Issue by greeven** [kfleischmann/geekhub#3]
Docker is running on an ubuntu server but i get an error doing `docker-compose up`:
```
dev@DevLnDocker01:~/geekhub$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

I'm not that fluent working via console only on an ubuntu server and thought it will be faster to ask instead of digging in on my own.

I probably did something wrong installing docker. Do you know by any chance how to fix this or to deal with it?

**Comment by kfleischmann** [comment]
You Need the latest docker compose Version.

greeven <notifications@github.com> schrieb am Di., 2. Okt. 2018, 15:52:
